build_utl:
  outputs:
    LAB2_WORK:
      account: "{{ env_var('DBT_ACCOUNT') }}"
      database: "{{ env_var('DBT_DATABASE') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: "{{ env_var('DBT_ROLE') }}"
      threads: 1
      schema: RAW_DATA_LAB2
      type: "{{ env_var('DBT_TYPE') }}"
      user: "{{ env_var('DBT_USER') }}"
      warehouse: "{{ env_var('DBT_WAREHOUSE') }}"
  target: LAB2_WORK
