build_utl:
  outputs:
    dev:
      account: NMB03811
      database: LAB2_WORK
      password: Utk@963007trips
      role: AccountAdmin
      schema: RAW_DATA_LAB2
      threads: 1
      type: snowflake
      user: UTKARSH9630
      warehouse: compute_wh
  target: dev
